### PR TITLE
FALCON-1932 Extension CLI should support common options

### PR DESCRIPTION
**Pull request by yzheng-hortonworks**
Tested CLI command with common options.

### CODE REVIEW

**Comment by bvellanki** [comment]
+1

**Comment by yzheng-hortonworks** [comment]
@sowmyaramesh To follow up with our talk, our current CLI framework doesn't check whether an option is used in a command or not, i.e. they are all optional. In other words, whether I add an option or not doesn't change your extension repository results, if you don't use these options. For example, "bin/falcon extension -enumerate -url http://localhost:15000 -d -ddd " gives the same result as "bin/falcon extension -enumerate -url http://localhost:15000".

This resembles with REST api design, i.e. it won't throw error if user pass an unrecognized parameter. Hope this resolves your concern.

If you want to be able to throw error for unsupported options, you need to change our CLI framework.

**Comment by sowmyaramesh** [comment]
@yzheng-hortonworks : There are two ways of handling it.
1> Instead of adding by default to Extension CLI it can be added only to commands which honor it. That way by default if unsupported option is passed it will throw exception. This is how it is handled today in the code
2> Other way is to handle in specific commands

As your code is in accordance with the current design I will give a ship ti. We can revisit this if required in the future. Thanks!

**Comment by sowmyaramesh** [comment]
+1

**Comment by yzheng-hortonworks** [comment]
Thanks @sowmyaramesh . Yes, and this would be a lot of work, since every CLI command only validates required parameters but not unsupported ones. We need to change every CLI command to make it happen.

**Pull request closed without merging**
