### PR TITLE
FALCON-1924 Falcon Coordinator rerun return old workflow id

### PR DESCRIPTION
**Pull request by PraveenAdlakha**

### CODE REVIEW

**Comment by PraveenAdlakha** [comment]
Earlier it used to be :  

Instances:
Instance		Cluster		SourceCluster		Status		Start		End		Details					Log
-----------------------------------------------------------------------------------------------
2016-04-19T09:00Z	uh1-gold	-	WAITING	2016-04-19T10:00Z	2016-04-19T10:07Z	-	http://hostname:port/oozie?job=0101865-160412100809625-oozie-oozi-W

Additional Information:
Response: RERUNRequest Id: 1615061750@qtp-1048027629-188 - deb1b68f-c721-4262-9a2e-4118dd7a73ab

Now it looks like :  

Consolidated Status: SUCCEEDED

Instances:
Instance		Cluster		SourceCluster		Status		Start		End		Details					Log
-----------------------------------------------------------------------------------------------
2016-01-12T01:00Z	local	-	SUSPENDED	2016-03-17T17:44Z	-	-	0000106-151229192519233-oozie-oozi-C@14

Additional Information:
Response: default/RERUN
Request Id: default/784135689@qtp-898694235-3 - 30e4621e-62cb-44ad-913c-6f8ca96ab5c3


We are supplying coord with action id

**Comment by pallavi-rao** [comment]
+1

**Comment by peeyushb** [comment]
@PraveenAdlakha Through this issue, are you trying to rerun the entire coordinator again instead of rerunning the failed workflow. Is it possible to provide some more details.

**Comment by PraveenAdlakha** [comment]
@peeyushb  The command i used to rerun was : 
$ bin/falcon instance -type process -name process6 -rerun -start 2016-01-12T01:00Z -end 2016-01-12T02:00Z


I was not trying to rerun the entire coordinator but one instance of the coordinator.Let me know if I am missing something.

**Comment by pallavi-rao** [comment]
@peeyushb, switching from workflow rerun to coord rerun was already taken care of in FALCON-1835. I have missed updating the results returned to return the coord id rather than workflow id. That is the change this PR handles

**Comment by peeyushb** [comment]
Thanks @PraveenAdlakha and @pallavi-rao  for clarification.

**Comment by peeyushb** [comment]
Patch looks good. +1 .

**Comment by sandeepSamudrala** [comment]
+1. LGTM

**Comment by peeyushb** [comment]
If no further comments, I will commit this patch soon.

**Pull request closed without merging**
