### PR TITLE
FALCON-1844 Replication to delete files removed in source by default

### PR DESCRIPTION
**Pull request by pallavi-rao**

### CODE REVIEW

**Comment by pavankumar526** [comment]
Looks good +1

**Comment by sandeepSamudrala** [comment]
:+1:  LGTM

**Comment by peeyushb** [comment]
Patch looks good. +1 .

**Comment by pallavi-rao** [comment]
Thanks @pavankumar526, @sandeepSamudrala, @peeyushb  for the review. Will merge shortly.

**Pull request closed without merging**
