### PR TITLE
FALCON-2120 falcon-regression build is failing because of CLI and hiv…

### PR DESCRIPTION
**Pull request by PraveenAdlakha**
…e changes

### CODE REVIEW

**Comment by pallavi-rao** [comment]
+1 from my end.

**Comment by sandeepSamudrala** [comment]
👍

**Comment by muraliramasami** [comment]
Thanks @PraveenAdlakha . 
1. I have cleaned up the local repos and executed the falcon-regression I didn't hit the pentaho-aggdesigner problem. 
2. After adding the falcon-cli dependency  we will hit the compilation error in RecipeMerlin. Since the constants related to recipes are removed and moved to "extension".

**Comment by pragya-mittal** [comment]
We no longer need the pentaho dependency, hence can go away with it. @PraveenAdlakha  please remove the cli dependency as murali will be taking care of it.

**Comment by PraveenAdlakha** [comment]
@pragya-mittal  I just verified we still need falcon-cli as its needed in Bundle.java.

**Comment by pragya-mittal** [comment]
@muraliramasami has already added the dependency as part of https://github.com/apache/falcon/pull/275. Please check.

**Comment by PraveenAdlakha** [comment]
@pragya-mittal  have removed it...please check now.

**Comment by pragya-mittal** [comment]
+1. Will merge the pull request tomorrow if there are no further comments.

**Pull request closed without merging**
