### PR TITLE
FALCON-1954 : Document enabling Oozie JMS for Falcon

### PR DESCRIPTION
**Pull request by vramachan**
Steps to enable Oozie JMS notification for Falcon.

### CODE REVIEW

**Comment by bvellanki** [comment]
Thanks for fixing merge conflicts. 👍 , will commit tomorrow if there are no further comments.

**Comment by vrangan** [comment]
+1 for the doc changes.   Can we create a separate JIRA if required for fixing these tests

==
org.apache.falcon.lifecycle.FeedExportIT.testSqoopExport
org.apache.falcon.lifecycle.FeedImportIT.testSqoopImport
org.apache.falcon.lifecycle.FeedImportIT.testSqoopHCatImport
org.apache.falcon.lifecycle.FeedImportIT.testSqoopImportUsingDefaultCredential
==

**Comment by vramachan** [comment]
@vrangan There is a JIRA (https://issues.apache.org/jira/browse/FALCON-1958) to figure out the intermittent IT test failures start happening since yesterday 5/11/16. 

But the IT test failure is a separate issue from this pull request.

**Comment by bvellanki** [comment]
+1 thank you very much for doing this, will commit shortly.

**Pull request closed without merging**
