### PR TITLE
FALCON-1906 upgrade falcon to java 8

### PR DESCRIPTION
**Pull request by PraveenAdlakha**

### CODE REVIEW

**Comment by peeyushb** [comment]
@PraveenAdlakha There are Falcon modules where source and target version is 1.7 for "maven-compiler-plugin". Can you just check other modules to upgrade to 1.8.

**Comment by PraveenAdlakha** [comment]
@peeyushb  have made the changes please review.

**Comment by bvellanki** [comment]
👍 Looks good to me. Please comment on end2end testing done for this Jira.

**Comment by vrangan** [comment]
Why do you want to disable JDK 7 support?

**Comment by PraveenAdlakha** [comment]
@vrangan Right now we are not using any code which is specific to java 8 so should not cause any problem,we can do testing for the same.

But we should migrate to java 8 as java 7 already had its end of life.Any suggestions that you have are welcome.

**Comment by vrangan** [comment]
There are  customers that still use JDK 7 as the platforms.     Building with JDK 7 does not preclude use of JDK 8 as the runtime platform.   So, we should defer until there is a real need to change the source compatibility to JDK 8

**Pull request closed without merging**
