### PR TITLE
FALCON-2014 Issue with submit idempotency in distributed mode.

### PR DESCRIPTION
**Pull request by pallavi-rao**

### CODE REVIEW

**Comment by sandeepSamudrala** [comment]
The same needs to be done for delete and update too.

**Comment by sandeepSamudrala** [comment]
Jenkins check has failed for the same for testUpdateAndTouch and testDelete.

**Comment by pallavi-rao** [comment]
The check makes no sense for delete. For update, the current stand is that we just overwrite old def with whatever the user supplies. So, not applicable for update either.

The tests are failing because they have duplicate submit statements. The fix just uncovered that mistake.

**Comment by sandeepSamudrala** [comment]
Makes sense.

**Comment by pallavi-rao** [comment]
I'm closing this pull request, as addressing the problem is not as simple as I initially thought. Will create a new pull request later.

**Pull request closed without merging**
