### PR TITLE
FALCON-2127: Falcon regression compilation issue and deleting depricated recipe test cases

### PR DESCRIPTION
**Pull request by muraliramasami**
This fix deletes the recipe bases test cases since the recipes are deprecated and moving to server side extensions. 
https://issues.apache.org/jira/browse/FALCON-634
Also fixes the current falcon regression compilation issues. 

The following files are deleted .
RecipeMerlin.java
MirrorWizardPage.java
HdfsRecipeTest.java
HiveDRTest.java
HiveDbDRTest.java
HiveObjectCreator.java
RecipeExecLocation.java
MirrorSourceTargetOptionsTest.java
MirrorSummaryTest.java
MirrorTest.java

### CODE REVIEW

**Comment by pragya-mittal** [comment]
+1. Just build it once to make sure regression is not failing.

**Comment by pragya-mittal** [comment]
Does it handle all the client dependency?

**Comment by muraliramasami** [comment]
Thanks @pragya-mittal . Yes. I have verified and compiled with the updated patch.

**Comment by pragya-mittal** [comment]
+1. Will merge it tomorrow if there are no further concerns.

**Pull request closed without merging**
