### PR TITLE
FALCON-1770 Update README file.

### PR DESCRIPTION
**Pull request by ajayyadava**
1. Renamed file to README.md.
2. Revisited the contents for some sections and reformatted some others.

### CODE REVIEW

**Comment by sriksun** [comment]
:+1:

**Comment by sandeepSamudrala** [comment]
Please add .md file to .gitignore for ignoring it.

**Comment by sandeepSamudrala** [comment]
other than that it LGTM.
:+1:

**Comment by sandeepSamudrala** [comment]
I meant not for .gitignore, but for front -end checking for the apache license key. Seems like it doesn't check for this file in front-end and rat plugins. Good to go.

**Comment by ajayyadava** [comment]
Thanks @sriksun  and @sandeepSamudrala  for reviewing. I will commit this using the new merge tool to test that.

**Pull request closed without merging**
