### PR TITLE
FALCON-2121 If a feed does not exist on a cluster, process submission throws NPE

### PR DESCRIPTION
**Pull request by pallavi-rao**
After the change:
`bin/falcon entity -submit -type process -file examples/entity/filesystem/pig-process.xml
ERROR: Bad Request;default/Feed in does not exist on cluster local2`

### CODE REVIEW

**Comment by sandeepSamudrala** [comment]
validateFeedDefinedForCluster is already available as helper method to validate.

Can you modify that method to get the same functionality?

**Comment by pallavi-rao** [comment]
@sandeepSamudrala, had totally missed the helper method. Used that instead.

**Comment by sandeepSamudrala** [comment]
looks good. 👍

**Comment by pallavi-rao** [comment]
Thanks @sandeepSamudrala for the review. Merging...

**Pull request closed without merging**
