### PR TITLE
FALCON-1790 CLI support for instance search

### PR DESCRIPTION
**Pull request by yzheng-hortonworks**
Tested CLI support. Also added documentation for both REST api and CLI.

### CODE REVIEW

**Comment by PraveenAdlakha** [comment]
please update the documentation for the search option.

**Comment by PraveenAdlakha** [comment]
Also just for my understanding is the code server side is already committed?

**Comment by yzheng-hortonworks** [comment]
@PraveenAdlakha Thanks for review. Yes, the code for REST api was committed to apache branch this morning. Also updated the documentation for both REST api and CLI.

**Comment by PraveenAdlakha** [comment]
+1 LGTM

**Comment by bvellanki** [comment]
👍 Ying, code looks good. If you can please add a negative test in FalconCLIIT, I will commit the change.

**Pull request closed without merging**
