### PR TITLE
FALCON-2057 HiveDR not working with multiple users and same DB

### PR DESCRIPTION
**Pull request by bvellanki**

### CODE REVIEW

**Comment by yzheng-hortonworks** [comment]
+1. Could you add documentation that falcon will create baseDir and user will create dbName and jobName? Could you also document that the user needs to be added to users group in order to run DR jobs? Thank you, @bvellanki .

**Comment by bvellanki** [comment]
@yzheng-hortonworks  This jira is not creating new behavior. It is fixing a bug in existing behavior. The users should not be aware of who creates what dir because the data stored under these dirs is "status of replication". This should be transparent to users.

**Comment by yzheng-hortonworks** [comment]
Could you add a comment to the code? So other developers would be aware of this? Thank you!

**Comment by vrangan** [comment]
+1

**Comment by bvellanki** [comment]
@yzheng-hortonworks  : I added comments  in code. Thank you for the review

**Comment by sowmyaramesh** [comment]
+1

**Pull request closed without merging**
