### PR TITLE
FALCON-2067 In instance status list, -allAttempts does not show all runs

### PR DESCRIPTION
**Pull request by pallavi-rao**
After the fix:
`$ bin/falcon instance -status -type process -name oozie-mr-process -start 2013-11-15T00:00Z -allAttempts
Consolidated Status: SUCCEEDED
Instances:
Instance		Cluster		SourceCluster		Status		Start		End		Details					Log
-----------------------------------------------------------------------------------------------
2013-11-15T00:05Z	local	-	READY	-	-	-	-
2013-11-15T00:05Z	local	-	KILLED	2016-07-14T05:53Z	2016-07-14T05:53Z	-	http://IM1738M1:11000/oozie?job=0000006-160713101246755-oozie-oozi-W
actions:
 user-action	ERROR	null
2013-11-15T00:05Z	local	-	KILLED	2016-07-14T05:48Z	2016-07-14T05:51Z	-	http://IM1738M1:11000/oozie?job=0000003-160713101246755-oozie-oozi-W
actions:
 user-action	ERROR	null
 failed-post-processing	KILLED	http://localhost:8088/proxy/application_1468321868387_0012/
2013-11-15T00:10Z	local	-	READY	-	-	-	-
2013-11-15T00:10Z	local	-	KILLED	2016-07-14T05:45Z	2016-07-14T05:48Z	-	http://IM1738M1:11000/oozie?job=0000004-160713101246755-oozie-oozi-W
actions:
 user-action	ERROR	null
 failed-post-processing	KILLED	http://localhost:8088/proxy/application_1468321868387_0011/
2013-11-15T00:15Z	local	-	KILLED	-	-	-	-
2013-11-15T00:20Z	local	-	KILLED	-	-	-	-
2013-11-15T00:25Z	local	-	KILLED	-	-	-	-
2013-11-15T00:30Z	local	-	KILLED	-	-	-	-
2013-11-15T00:35Z	local	-	KILLED	-	-	-	-`

### CODE REVIEW

**Comment by peeyushb** [comment]
+1. Looks Good.

**Comment by pallavi-rao** [comment]
Build failure is unrelated. 

@pragya-mittal, please check if the output of the command is to your satisfaction. Will merge once you +1.

**Comment by PraveenAdlakha** [comment]
+1

**Comment by pallavi-rao** [comment]
Got a +1 from @pragya-mittal offline. Thanks @peeyushb, @PraveenAdlakha

**Pull request closed without merging**
