### PR TITLE
FALCON-1936 Extensions related files are not available in distro packaging

### PR DESCRIPTION
**Pull request by sowmyaramesh**

### CODE REVIEW

**Comment by peeyushb** [comment]
@sowmyaramesh Thanks for working on this. Just want to know , is it possible to simplify the packaging statements by copying extensions related files to hdfs-mirroring, hive-mirroring and hdfs-snapshot-mirroring respectively instead of having META, build and runtime directory. For any specific jar we can have lib directory under respective extensions.

**Comment by sowmyaramesh** [comment]
@peeyushb : don't understand your comment. Idea is to maintain the extension store structuring

ExtensionUri
|-- Extension1
    |-- README
    |-- META
    |-- libs
        |-- build
        |-- runtime
    |-- resources
        |-- build
        |-- runtime

**Comment by vrangan** [comment]
+1
Thanks @sowmyaramesh   - When I first ran with testpatch, some unrelated tests failed - cleaned up env and revalidated

**Comment by peeyushb** [comment]
@sowmyaramesh I just wanted to say that, is it possible to simplify the extension directory structure as below rather having META, resources, build, runtime directory 
ExtensionUri
|-- Extension1
    |-- libs
    |-- Extension1-properties.json
    |-- Extension1-template.xml
    |-- Extension1-workflow.xml

Please help me to understand about the purpose of having META, build and runtime directory.

**Comment by sowmyaramesh** [comment]
@peeyushb : Please refer FALCON-634. Having a definitive directory structure helps. In future when custom extensions are implemented extension store dir structure will be self explanatory to the user.

**Pull request closed without merging**
