### PR TITLE
FALCON-1986 logFile retrieved when getting process instance status sh…

### PR DESCRIPTION
**Pull request by pallavi-rao**
…ould be a link that points to logs

### CODE REVIEW

**Comment by sandeepSamudrala** [comment]
looks good

**Comment by peeyushb** [comment]
Patch looks good. +1.

**Comment by bvellanki** [comment]
👍  this is useful

**Comment by pallavi-rao** [comment]
Thanks @sandeepSamudrala, @peeyushb, @bvellanki for the review. Merging the request to both 0.10 and trunk.

**Pull request closed without merging**
