### PR TITLE
FALCON-2076 Server fails to start since extension.store.uri is empty in startup.properties

### PR DESCRIPTION
**Pull request by bvellanki**

### CODE REVIEW

**Comment by bvellanki** [comment]
@pragya-mittal  @pallavi-rao @vrangan : It is a one line change, I tested it. Please review

**Comment by pallavi-rao** [comment]
+1. Thanks @bvellanki

**Comment by sandeepSamudrala** [comment]
👍

**Comment by pallavi-rao** [comment]
Unrelated build failure. Merging.

**Pull request closed without merging**
