### PR TITLE
Falcon-1881 : Database export does not require fields tag in entity specification

### PR DESCRIPTION
**Pull request by vramachan**
Database export does not require fields tag in entity specification

### CODE REVIEW

**Comment by pallavi-rao** [comment]
Is the intention of the change to make fields (includes and excludes) optional or is it to remove the ability to specify the include/exclude fields? If it is latter, why are we doing it?

**Comment by vramachan** [comment]
@pallavi-rao For export, <fields> needs to go because it is superfluous. The list of fields that gets exported to database is determined by the target table definition. If the target table definition has 3 fields, then only 3 fields from the HDFS will be exported. 

For import, we need the fields explicitly specified by the user. 

The way this is implemented now is to do a check in the EntityParser to validate the Export does not have <fields> tag.

**Comment by peeyushb** [comment]
@vramachan Thanks for adding the details. Patch looks good. +1.

**Comment by bvellanki** [comment]
+1 for the patch. Will commit shortly.

**Pull request closed without merging**
