### PR TITLE
FALCON-2118:  Proposal for new UI changes

### PR DESCRIPTION
**Pull request by vrangan**
changes as described in FALCON-2118

### CODE REVIEW

**Comment by peeyushb** [comment]
+1. Looks good.

**Comment by peeyushb** [comment]
Pull Request has been reviewed and merged into branch 0.10-refactored-ui. Thanks @vrangan.

**Comment by vrangan** [comment]
Peeyus

**Comment by vrangan** [comment]
this has been merged into the 0.10-refactored -ui branch - closing pull request

**Pull request closed without merging**
