### PR TITLE
FALCON-1107: Move trusted extensions processing to server side

### PR DESCRIPTION
**Pull request by sowmyaramesh**
Ignore any documentation issues as it will be addressed in https://issues.apache.org/jira/browse/FALCON-1106. Thanks!

### CODE REVIEW

**Comment by bvellanki** [comment]
@sowmyaramesh  :+1: for the patch. It is long one and I did a couple of sweeps through it.  Thank you for porting Falcon-1880 patch to server side extensions. 

Please leave a comment describing the end2end testing you did for future reference.

**Comment by sowmyaramesh** [comment]
@bvellanki :
This request has the unit tests. I have also done manual testing to ensure it works.
FALCON-1789 implements the REST API and CLI support for extensions and Ying will be uploading the patch soon. She has confirmed that REST API's and CLI's added works. IT tests should be added as part of FALCON-1789. Thanks for the review!

**Comment by vrangan** [comment]
Thanks @sowmyaramesh.   I think we need to document making sure people upgrading are fully aware of the changes in terms of externally visible changes.   

+1

**Comment by sowmyaramesh** [comment]
@vrangan : I keep that in mind when I update the documents. Thanks!

**Pull request closed without merging**
