### PR TITLE
FALCON-1793 : Feed element action="archive" is submittable via command line tool falcon

### PR DESCRIPTION
**Pull request by deepakbarr**
Submit command output - 

$ bin/falcon entity -submit -type feed -file examples/entity/filesystem/out-feed.xml
ERROR: Bad Request;local/ARCHIVE action type is not supported for retention

### CODE REVIEW

**Comment by pallavi-rao** [comment]
We should also update feed-0.1.xsd to keep only "delete" and remove the rest. If that is done an explicit validateFeedRetention may not be required.

**Comment by pallavi-rao** [comment]
Please also update CHANGES.txt

**Comment by deepakbarr** [comment]
I agree @pallavi-rao  !

**Comment by deepakbarr** [comment]
Closing the review request. Will create new.

**Comment by ajayyadava** [comment]
@deepakbarr  you don't need to close the pull request, you can just update the same pull request, the build will also trigger automatically.

**Pull request closed without merging**
