### PR TITLE
FALCON-1804. Non-SLA feed throws NullPointerException

### PR DESCRIPTION
**Pull request by sandeepSamudrala**

### CODE REVIEW

**Comment by pavankumar526** [comment]
Looks good

**Comment by pallavi-rao** [comment]
+1. Will merge once the build validation completes

**Comment by PraveenAdlakha** [comment]
LGTM.

**Comment by ajayyadava** [comment]
:+1:  @sandeepSamudrala can you please resolve the conflict in CHANGES.txt?

**Comment by sandeepSamudrala** [comment]
@ajayyadava : I rebased the pull request. This doesn't seem to be working of resolving conflicts each time.

**Comment by sandeepSamudrala** [comment]
Can this be committed?

**Pull request closed without merging**
