### PR TITLE
FALCON-1917 Fix build failure

### PR DESCRIPTION
**Pull request by sowmyaramesh**

### CODE REVIEW

**Comment by yzheng-hortonworks** [comment]
+1

**Comment by sowmyaramesh** [comment]
Thanks for the quick review @yzheng-hortonworks . Will commit once build succeeds.

**Comment by vrangan** [comment]
+1

**Comment by peeyushb** [comment]
I have applied the patch and build works fine. +1 .

**Comment by peeyushb** [comment]
I will commit this patch to avoid further build failure.

**Comment by PraveenAdlakha** [comment]
+1

**Pull request closed without merging**
