### PR TITLE
FALCON-1938 : Add support to execute Spark SQL process

### PR DESCRIPTION
**Pull request by peeyushb**

### CODE REVIEW

**Comment by vrangan** [comment]
Looks like we missed this earlier.   Thanks for fixing this

+1

**Comment by bvellanki** [comment]
+1 will commit

**Comment by bvellanki** [comment]
@peeyushb  : The jenkins build failed. Can you please verify what is happening before committing the code?

**Comment by peeyushb** [comment]
@bvellanki I have checked and found that build failure is not related due to the patch in this pull request.

**Pull request closed without merging**
