### PR TITLE
FALCON-1976 and FALCON-1977:  Remove hadoop-2 profile and move unit t…

### PR DESCRIPTION
**Pull request by vrangan**
Removed hadoop-2 profile and moved falcon-unit to addons

### CODE REVIEW

**Comment by peeyushb** [comment]
@vrangan I have tried to build the Falcon with the patch in pull request. When I use "mvn clean install" build fails in examples module. It looks like that testng dependency is required explicitly now.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project falcon-examples: groups/excludedGroups require TestNG or JUnit48+ on project test classpath -> [Help 1]`


But when I use "mvn clean install -Ptest-patch", build succeeds . Earlier also it succeeded by using hadoop-2 profile.

**Comment by vrangan** [comment]
@peeyushb   I got that error without test-patch earlier also.  Let me see if there is a way to to fix it or is it specific to maven versions as removing the profile did not change the dependencies being managed

**Comment by vrangan** [comment]
Failures are unrelated to this change.   Passes successfully locally.

**Comment by bvellanki** [comment]
+1 build works for me, will commit if there are no further comments.

**Comment by bvellanki** [comment]
[INFO] --- maven-assembly-plugin:2.6:assembly (default-cli) @ falcon-main ---
[INFO] Reading assembly descriptor: src/main/assemblies/assembly-src.xml
[INFO] Copying files to /Users/bvellanki/SourceCode/apache-falcon/falcon/target/falcon-0.10-SNAPSHOT-notes
[WARNING] Assembly file: /Users/bvellanki/SourceCode/apache-falcon/falcon/target/falcon-0.10-SNAPSHOT-notes is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Falcon ...................................... SUCCESS [02:15 min]
[INFO] Apache Falcon UI ................................... SUCCESS [  8.062 s]
[INFO] Build Tools ........................................ SUCCESS [  4.759 s]
[INFO] Apache Falcon Java client .......................... SUCCESS [ 31.087 s]
[INFO] Apache Falcon Metrics .............................. SUCCESS [ 20.956 s]
[INFO] Apache Falcon Hadoop Dependencies .................. SUCCESS [ 14.534 s]
[INFO] Apache Falcon Test Utility ......................... SUCCESS [  8.538 s]
[INFO] Apache Falcon Commons .............................. SUCCESS [02:09 min]
[INFO] Apache Falcon CLI client ........................... SUCCESS [ 12.894 s]
[INFO] Apache Falcon Oozie EL Extension ................... SUCCESS [ 11.549 s]
[INFO] Apache Falcon Embedded Hadoop - Test Cluster ....... SUCCESS [ 23.295 s]
[INFO] Apache Falcon Sharelib Hive - Test Cluster ......... SUCCESS [  2.058 s]
[INFO] Apache Falcon Sharelib Pig - Test Cluster .......... SUCCESS [  0.993 s]
[INFO] Apache Falcon Sharelib Hcatalog - Test Cluster ..... SUCCESS [  0.777 s]
[INFO] Apache Falcon Sharelib Oozie - Test Cluster ........ SUCCESS [  0.368 s]
[INFO] Apache Falcon Test Tools - Test Cluster ............ SUCCESS [  0.341 s]
[INFO] Apache Falcon Messaging ............................ SUCCESS [ 27.373 s]
[INFO] Apache Falcon extensions ........................... SUCCESS [ 21.795 s]
[INFO] Apache Falcon LIfecycle Module ..................... SUCCESS [ 24.443 s]
[INFO] Apache Falcon Oozie Adaptor ........................ SUCCESS [01:09 min]
[INFO] Apache Falcon Scheduler ............................ SUCCESS [01:23 min]
[INFO] Apache Falcon Acquisition .......................... SUCCESS [  0.984 s]
[INFO] Apache Falcon Distcp Replication ................... SUCCESS [ 16.677 s]
[INFO] Apache Falcon Retention ............................ SUCCESS [ 16.594 s]
[INFO] Apache Falcon Archival ............................. SUCCESS [  0.950 s]
[INFO] Apache Falcon Rerun ................................ SUCCESS [ 23.557 s]
[INFO] Apache Falcon Prism ................................ SUCCESS [02:04 min]
[INFO] Apache Falcon Unit ................................. SUCCESS [02:44 min]
[INFO] Apache Falcon Examples ............................. SUCCESS [  1.629 s]
[INFO] Apache Falcon Hive Replication ..................... SUCCESS [01:10 min]
[INFO] Apache Falcon HDFS Snapshot Replication ............ SUCCESS [02:11 min]
[INFO] Apache Falcon Web Application ...................... SUCCESS [18:32 min]
[INFO] Apache Falcon Documentation ........................ SUCCESS [  8.045 s]
[INFO] Apache Falcon Distro ............................... SUCCESS [ 45.134 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39:18 min
[INFO] Finished at: 2016-05-23T13:14:42-07:00
[INFO] Final Memory: 313M/798M
[INFO] ------------------------------------------------------------------------
Shutting down hive metastore.
[INFO] Shutdown hook executing
[INFO] Shutdown hook complete
bvellanki@HW11014:~/SourceCode/apache-falcon/falcon (master)$

**Comment by bvellanki** [comment]
Command used to build after applying patch is 

"mvn clean verify assembly:assembly -Ptest-patch"

**Comment by yzheng-hortonworks** [comment]
Build succeeded. +1.

**Pull request closed without merging**
